### ISSUE TITLE
Bug following changes to the tensor creation API in torch v2.2

### ISSUE THREAD

**Issue by jatkinson1000** [Cambridge-ICCS/FTorch#100]
When building against libtorch v2.2.1 I am able to build FTorch successfully.
I am also able to subsequently build the examples.
However, I get a runtime error:
```
[ERROR]: Unknown layout
```

It seems that this is possibly an issue with the move from torch v2.1 to v2.2 - see [here](https://github.com/Vahe1994/AQLM/issues/20).
This is confirmed if I build against libtorch v2.1 obtained from e.g.(this is v2.1 cuda 11.8 compatible).
```
wget https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.1.2%2Bcu118.zip
unzip libtorch-cxx11-abi-shared-with-deps-2.1.2%2Bcu118.zip
```

It appears that the error is being thrown from [here (torch source)](https://github.com/pytorch/pytorch/blob/09cb42ce29bc9c2909ec99b648ed3711d1fa639b/c10/core/Layout.h#L74).

The Torch docs note that the `torch.layout` argument is "beta and subject to change" - see [here](https://pytorch.org/docs/stable/tensor_attributes.html#torch-layout) but I can't see that anything recent has happened.
I have tried amending our source to be explicit with the `layout` in `TensorOptions` by amending [this line](https://github.com/Cambridge-ICCS/FTorch/blob/aaa82bd6b7cb5b44a3c245830d864432222a0d89/src/ctorch.cpp#L127) to be
```
torch::TensorOptions().dtype(get_dtype(dtype)).layout(torch::kStrided)).to(get_device(device));
```
as indicated from the [Tensor creation API docs](https://pytorch.org/cppdocs/notes/tensor_creation.html).
This builds OK as before, but still produces the same error at runtime.

So the current state is I am unsure if this is something we need to address and change, or something that is maybe fixed upstream and coming in v2.2.2 as the closure of [this PyTorch issue](https://github.com/pytorch/pytorch/issues/120020) (maybe??) suggests.

If I understand correctly this can be resolved by requiring `gcc >= 9`.

Next steps would be building against the nightly release from https://download.pytorch.org/libtorch/nightly/cu118/libtorch-cxx11-abi-shared-with-deps-latest.zip to see if there is indeed an upstream fix. However, I can't do this on Derecho as it has a fairly limited software stack. I may try on CSD3 which is broader.
Need either cuda/11.8 + gcc/9-11 or cuda/12.1

**Comment by jatkinson1000** [comment]
@jwallwork23, @ElliottKasoar, @TomMelt Would appreciate your thoughts on this as people who are a bit more in touch with c++ than I.

The installed version of libtorch on CESM that we are currently trying to build against is v2.2.1.

**Comment by ElliottKasoar** [comment]
From a quick test with libtorch 2.2.2 and gcc 7, 9, and 11, it does indeed seem to be resolved by updating gcc >= 9, which matches the requirement for building from source in the latest [release notes](https://github.com/pytorch/pytorch/releases/tag/v2.2.2), and more generally the requirement for [full C++17 compatibility that we noted](https://github.com/Cambridge-ICCS/FTorch/issues/34).

It's interesting that there's a slight mismatch between the check and the README, which suggests it should actually be gcc>=9.4.0, and that it doesn't raise the same error I saw.

**Comment by jatkinson1000** [comment]
Oh nice, v2.2.2 was released 2 hrs ago!!

The release notes suggest >= 9.0: https://github.com/pytorch/pytorch/releases/tag/v2.2.2

Suggest we resolve this by enforcing gcc >= 9.0 in our CMake.
And this implies that FTorch has to be built with g++, not icpc?? I know we've been back and forth on this one a bit... #54 

Now I need to try and resolve the issue of cuda wanting <= 11 on Derecho -_-

**Comment by TomMelt** [comment]
I think that's just the release notes stating that for _this_ release the `gcc` requirement has changed to `gcc>= 9.0`. Not that you have to use `gcc`.

**Comment by TomMelt** [comment]
A couple lines below there is this comment:
> Fix building from source on Windows source MSVC 14.38 - VS 2022 (#122120)

Which, to me, implies they also support the windows c++ compiler.... though I wouldn't quote me on it :flushed:

**Comment by jatkinson1000** [comment]
Closing as not re-emerged since enforcing CXX 17.
Users can re-open if they encounter it in future.
