### ISSUE TITLE
Fortran compatibility

### ISSUE THREAD

**Issue by ElliottKasoar** [Cambridge-ICCS/FTorch#130]
We should probably explicitly state which Fortran standards we support. 

Ideally, we might test against different standards, if that's possible (maybe via the `-std` gfortran compile flag - if so, we may want to open a separate issue, and keep this one focused on documentation)?

**Comment by jatkinson1000** [comment]
My thoughts here are can we write something to test this automatically?

Like a workflow that iterates over the various standards and builds FTorch with different flags?

**Comment by jatkinson1000** [comment]
Discussion with @TomMelt We will set FTorch to require Fortran 2008 in the documentation.
See comments on #145 for further development.
