### ISSUE TITLE
Project/Repository Naming

### ISSUE THREAD

**Issue by jatkinson1000** [Cambridge-ICCS/FTorch#15]
We have discussed that fortran-pytorch-lib might not be the nicest most catchy name for the project.

We should settle on a name before first release.

Currently we build a file called ftorch, could we call the project FTorch perhaps?

Disadvantages:

- perhaps less clear what it does ("FTorch: a library of fortran PyTorch bindings")
- No similarly nice equivalent for TensorFlow... "FTF" isn't great... "FTensorFlow" sounds weird.

**Comment by jatkinson1000** [comment]
@SimonClifford @mondus @dorchard @christopheredsall Any thoughts here?

**Comment by jatkinson1000** [comment]
One further comment would be that we have discussed that fact that this library could also be a C-PyTorch interface (a byproduct of needing to go via C to get to C++).

Would we want to leave this open as an option in naming?

**Comment by TomMelt** [comment]
Here's my take:

1. I think `FTorch` is a great name :+1: 
2. I am pitching `TensorFort` for the tensorflow variant.

I don't think they need the same naming scheme. Just something thats short and kind of relevant.

**Comment by jatkinson1000** [comment]
Counterpoint 🎼 🎶 : TensorFort brings us into overlap with TorchFort.
Whilst the same scheme is not required it would be nice if we could standardise.
Part of me does still like the idea if making the 'Fortran' part more explicit.
