### ISSUE TITLE
overload `torch_tensor_delete`

### ISSUE THREAD

**Issue by TomMelt** [Cambridge-ICCS/FTorch#153]
overload `torch_tensor_delete` so we no longer have to delete each element of input/output tensor manually.

It could just take the array and loop over the bounds :ok_hand: 

https://github.com/Cambridge-ICCS/FTorch/blob/490272ef5662936be26697d496b14f6a281214fa/src/ftorch.f90#L274-L286

**Comment by jatkinson1000** [comment]
@TomMelt Was this closed in #156 ?

**Comment by jatkinson1000** [comment]
This was indeed closed.
