### ISSUE TITLE
Possibly use overloading in the API for dealing with multiple inputs 

### ISSUE THREAD

**Issue by dorchard** [Cambridge-ICCS/FTorch#16]
We could use overloading in Fortran 90 to provide a simpler interface.
Here's an example of overloading based on arity: https://gist.github.com/dorchard/3cc13fe75d6d109cb75ec11d41ddc104
(Note something similar can work for overloading on input type too)

**Comment by jatkinson1000** [comment]
This has been dealt with elsewhere by implementing fypp approach in #60.
