### ISSUE TITLE
torch_tensor_from_array cannot convert 5D array into torch tensor

### ISSUE THREAD

**Issue by smhassanerfani** [Cambridge-ICCS/FTorch#172]
I'm working with ConvLSTM. It normally receives input data in 5 dimensions: `batch_size x sequence_length x channels x height x width`. when I use the following snippet:
      
```
      type(torch_model) :: model
      type(torch_tensor), dimension(1) :: in_tensors

      ! Set up the model inputs and output as Fortran arrays (data structures)
      real(wp), dimension(:,:,:,:,:), allocatable, target :: in_data ! 5D input tensor (BS, SL, C, H, W)

      integer, parameter :: in_dims = 5
      integer :: in_shape(in_dims) = [1, 48, 5, 100, 154]
      integer :: in_layout(in_dims) = [1, 2, 3, 4, 5]

      integer, parameter :: input_tensor_length = 3696000
      inp_filename = "./data/input_tensor.dat"

      allocate(in_data(in_shape(1), in_shape(2), in_shape(3), in_shape(4), in_shape(5)))

      call load_data(inp_filename, input_tensor_length, in_data)
      call torch_tensor_from_array(in_tensors(1), in_data, in_layout, torch_kCPU)
```

I run into this error:

`Error: There is no specific subroutine for the generic ‘torch_tensor_from_array’ at (1)`

**Comment by jatkinson1000** [comment]
Thanks for opening this issue @smhassanerfani 

We have to explicitly declare functions for every possible rank (rules of Fortran 😉) and we only catered for up to rank 4 tensors in the current version of the library.

I have just made a change to accommodate 5d tensors in the `5d-tensors` branch here: https://github.com/Cambridge-ICCS/FTorch/tree/5d-tensors

Please could you pull that branch, re-build FTorch, and let me know if that now works for you?
If it does I'll set up a pull request to bring it into the main code.

Whilst we are on the subject - is 5-D the highest rank you are likely to need, or is it worth extending to 6 or more?

**Comment by smhassanerfani** [comment]
Thank you for your prompt response. I checked my snippets and ran into a `multi-head` model receiving data in the following format: `x = torch.randn((2, 48, 5, 10, 100, 154))`, representing `batch_size x sequence_length x channels x levels x width x height`. In this instance, `levels` represent different vertical levels for aerosol concentration at various pressure levels in the atmosphere. I might even go crazier than this.

I will clone the new branch you kindly created and let you know how it goes later today. I need to run into a meeting now.

**Comment by smhassanerfani** [comment]
However, I believe 5D is fair enough to contend with for the time being.

**Comment by smhassanerfani** [comment]
For the record:

1. I cloned the repository again and checked out the new branch `5d-tensors`.
2. I used `git diff main..5d-tensors` to find new subroutines.
3. @jatkinson1000 added new subroutines to `ftorch.f90` using the same interface as `torch_tensor_from_array`.
4. I ran `cmake` in `FTorch/src` again (I guess I didn’t need to `cmake` from scratch; maybe just running `make` in the build directory would have worked).
5. I ran my code again, and it worked well.

**Comment by jatkinson1000** [comment]
Thanks for confirming @smhassanerfani

I'm re-opening this as I have a pull request over at #173 that will bring this functionality back into the main code.
Once this is merged I'll close this.

A couple of other things:
- Yes, you probably could have avoided re-running cmake from scratch in this case, but it can be very fickle, so for a relatively small project such as this it is sometimes easier to re-do it all for peace of mind.
- Please do cite us if you have any work involving FTorch (we are hoping for a release paper before too long).
- If you have any projects using FTorch and would like them to be featured on our README/documentation do let us know.

**Comment by jatkinson1000** [comment]
@smhassanerfani This is now in the `main` branch of the code for you and others to use.
