### ISSUE TITLE
Use reusable workflows

### ISSUE THREAD

**Issue by jwallwork23** [Cambridge-ICCS/FTorch#201]
We could use reusable workflows to make it easier if we ever want to add another test workflow. I can look into this as a follow-up.

_Originally posted by @jwallwork23 in https://github.com/Cambridge-ICCS/FTorch/pull/168#discussion_r1875681977_

**Comment by jatkinson1000** [comment]
@jwallwork23 based on #202 should this be closed as not-planned?

**Comment by jwallwork23** [comment]
> @jwallwork23 based on #202 should this be closed as not-planned?

Yeah I think so, will close.
