### ISSUE TITLE
Installation instructions may need to account for PyTorch weirdness

### ISSUE THREAD

**Issue by SimonClifford** [Cambridge-ICCS/FTorch#28]
PyTorch installations can sometimes lead to a situation where CUDA is needed by libtorch but is not available on the host system (perhaps because it doesn't have a GPU).  A solution is to install pytorch from a CPU only repository:

    pip install torch --index-url https://download.pytorch.org/whl/cpu

It might be argued that this isn't our problem?

**Comment by jatkinson1000** [comment]
I believe this was sufficiently tackled in #49 with a note provided in the README saying that users may need to be careful and use `--index_url` to specify cpu vs cuda versions to download.

Closing.
