### ISSUE TITLE
Misleading comment

### ISSUE THREAD

**Issue by ElliottKasoar** [Cambridge-ICCS/FTorch#45]
Comments in ftorch.f90 describing the device to specify when running on GPUs suggest [torch_kGPU](https://github.com/Cambridge-ICCS/FTorch/blob/main/src/ftorch.f90#L54), as opposed to the correct [torch_kCUDA](https://github.com/Cambridge-ICCS/FTorch/blob/main/src/ctorch.h#L29).

**Comment by jatkinson1000** [comment]
Thanks Elliot - this is why testing in practice is better than 'works in theory'!!
If you can correct with a quick PR that would be great.
I'm intrigued to see how one might get the mps or xpu backends to work...

**Comment by ElliottKasoar** [comment]
Resolved by #49
