### ISSUE TITLE
Ambiguous description of pt2ts.py

### ISSUE THREAD

**Issue by ElliottKasoar** [Cambridge-ICCS/FTorch#52]
The description of pt2ts.py in the [utils README](https://github.com/Cambridge-ICCS/FTorch/blob/main/utils/README.md) could be interpreted that the model will be saved in the same directory as the pt2ts.py file, but it is instead saved in the directory that pt2ts.py is called from.

Two potential solutions are:

1. Update the README to make the distinction clear
2.  Update pt2ts.py (in quite a few places, including the benchmark repo) to get its location, and prepend this to the save path, and clarify this in the README

I would lean towards the latter, so the location is more consistent.

For example, pt2ts.py might be called from the model directory, a build directory, or the directory up containing (such as from a script like [run_benchmarks.sh](https://github.com/Cambridge-ICCS/FTorch-benchmarks/blob/main/run_benchmarks.sh)), each of which currently would save the model in a different location.

**Comment by ElliottKasoar** [comment]
Reading it again, perhaps the description is clear enough at the moment, so the question is maybe more whether (by default) pinning the location to the same directory as pt2ts.py would be preferable?

**Comment by jatkinson1000** [comment]
I agree, if running the script from in `build/` for some reason to regenerate the model we should expect it to be output in the same place.

We can probably do this with a relatively small change (and hidden from the user) using the `path` package.
IIRC there is a command (or maybe two) to get the parent of the script that is currently running.

**Comment by jatkinson1000** [comment]
I'm revisiting this, and under the "principle of least surprise" I think the file appearing wherever you are locally calling `pt2ts.py` from is actually the more logical option.

Any thoughts @ElliottKasoar?
I'm trying to clear out some simple issues so can update the docs to be clearer on this if you think that is OK?

**Comment by ElliottKasoar** [comment]
In retrospect, yes I'd say the user's current working directory is probably the most logical place, so I'm happy with the current functionality remaining the same.

Ideally it might be nice to have the output filename as an optional argument, which the [comments](https://github.com/Cambridge-ICCS/FTorch/blob/main/utils/pt2ts.py#L124) suggest may already be possible, but I think `sys.argv` is only used at the end for the check that the model file was created, which is confusing.

I might be missing something though, and if not, it's probably worth a separate issue.

**Comment by jatkinson1000** [comment]
Ah, this is a good spot @ElliottKasoar Thanks.

Looks like @jwallwork23 added the option to pass a filename in, but as you say only used it at the end.
In this case I agree that #171 should use that input everywhere for the filename if provided (with the default being as it currently operates).

I'll make those updates when I can and tag you again for a review if that's OK?
