### ISSUE TITLE
GPU example and documentation

### ISSUE THREAD

**Issue by jatkinson1000** [Cambridge-ICCS/FTorch#71]
It is not intuitive that when running for GPU the input should be put on CUDA, but the output should NOT (thanks @ElliottKasoar for pointing this out).

We should clearly document this somewhere, and provide an example of running on GPU.

**Comment by ElliottKasoar** [comment]
Just to note there is a small note in the [GPU section](https://github.com/Cambridge-ICCS/FTorch#4-running-on-gpus) of the README, although it's unnecessarily specific to `torch_tensor_from_blob`, and quite hidden away! An example would definitely help.

**Comment by jwallwork23** [comment]
Was this addressed sufficiently by #96?

**Comment by jatkinson1000** [comment]
Yes, I believe so, so will close. Thank you.
