### ISSUE TITLE
Add optimisation options/guidance

### ISSUE THREAD

**Issue by ElliottKasoar** [Cambridge-ICCS/FTorch#81]
As discussed in #78, there are (at least) two forms of optimisation that would be relatively straight forward to facilitate in some capacity, but require more consideration/are unlikely to be the default options (which is why they are not included in the referenced PR):

1. Model freezing
  - See: [torch.jit.freeze](https://pytorch.org/docs/stable/generated/torch.jit.freeze.html)
  - Applies [system-independent optimization](https://discuss.pytorch.org/t/when-to-torch-jit-freeze-for-deployment/135063), as opposed to the system-dependent `optimize_for_inference` (which is currently [broken](https://github.com/Cambridge-ICCS/FTorch/blob/main/utils/pt2ts.py#L24), unfortunately)
  - Can give up to [50% speedup](https://pytorch.org/tutorials/prototype/torchscript_freezing.html)
  - From [our benchmarking](https://github.com/Cambridge-ICCS/FTorch-benchmarks/blob/30012999a3ab03afcdf00ce519bfd88d527b726a/utils/visualise.ipynb) (see `FTorch with/without gradients and/or frozen models` sections), freezing the model can make more modest, but not insignificant, improvements (in most cases)
    - Tests were carried out by replacing `scripted_model.save(filename)` with  `frozen_model = torch.jit.freeze(scripted_model)`, and then `frozen_model.save(filename)` in [pt2ts.py](https://github.com/Cambridge-ICCS/FTorch/blob/main/utils/pt2ts.py)
  - While not a problem for the use of FTorch, it's also worth noting that running the same TorchScript via Forpy (on CPU or GPU) seemed to give a similar errors to what `optimize_for_inference` can gives e.g. `AttributeError: 'RecursiveScriptModule' object has no attribute 'training'`
  - Freezing the model appears to lead to numerical errors (~10^-6) for the ResNet benchmark, raising a [RuntimeError](https://github.com/Cambridge-ICCS/FTorch/blob/main/utils/pt2ts.py#L156) when saving, but this doesn't seem to be the case for the cgdrag benchmark, and it is unclear why
  - The **guidance** part of the title is perhaps most relevant here, as this is less about the main FTorch library, and more about how we enable users to use tools like `pt2ts.py` as part of a workflow involving FTorch
    - This is somewhat dependent on the typical familiarity of potential FTorch users with the processes involved in saving to TorchScript
    - Note: [`trace_to_torchscript`](https://github.com/Cambridge-ICCS/FTorch/blob/main/utils/pt2ts.py#L30) currently uses model freezing. It would be preferable to have a shared setting and/or behaviour, unless there is a clear reason to use freezing in only one of the functions
    - Any guidelines on `trace_to_torchscript` compared with `script_to_torchscript` may also be useful, as currently there is no clear motivation not to use the "default" `script_to_torchscript`

2. InferenceMode
- See: [inference mode](https://pytorch.org/cppdocs/notes/inference_mode.html), [autograd mechanics](https://pytorch.org/docs/1.9.0/notes/autograd.html) and the [dev podcast](https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5zaW1wbGVjYXN0LmNvbS9PQjVGa0lsOA/episode/OWVmNjk3M2QtNjY2Ni00MmYyLTg4MTQtZWE3MDZiYjU2N2Rk?)
-  From [our benchmarking](https://github.com/Cambridge-ICCS/FTorch-benchmarks/blob/30012999a3ab03afcdf00ce519bfd88d527b726a/utils/visualise.ipynb) (see `FTorch with InferenceMode and NoGradMode` sections), benefits were less clear, but in general it is expected to be at least as fast
    - Tests were carried out by replacing `torch::AutoGradMode enable_grad(requires_grad);` with `c10::InferenceMode guard(requires_grad);` in all ctorch.cpp functions, but ideally both options would be presented to users
  - This mode was only added (as a beta) in PyTorch 1.9, so we would need to consider support for older versions
  - The mode is also much stricter than [`NoGradMode`](https://pytorch.org/cppdocs/api/typedef_namespacetorch_1abf2c764801b507b6a105664a2406a410.html#_CPPv4N5torch11NoGradGuardE), so cannot be used in all cases

**Comment by jatkinson1000** [comment]
Closing as broken down into #112 and #113
