### ISSUE TITLE
How to use low-version intel compiler to compile Ftorch ?

### ISSUE THREAD

**Issue by KingLLee** [Cambridge-ICCS/FTorch#83]
Recently, I want to use a AI model from python in General Circulation Model (GCM) which depends on the compiler version of 2017, but this ftorch module should be compiled by the intel compiler version of 2021. I wonder how to solve this problem and whether ftorch can be compiled in low-version intel compiler like 2017 or not?

**Comment by KingLLee** [comment]
Worth to note that libtorch may depend on high-version intel compiler. Considering that, using low-version compiler isn't a good way of resolution, and maybe there are other ways to use AI model in fortran code, i.e. hard coding in fortran or some others methods. Hope your advice.

**Comment by jatkinson1000** [comment]
Hi @KingLLee 
I'm not sure we stipulate anywhere that intel 2021 is required, can you tell us why you got that impression?

We have tested with various versions of the intel OneAPI suite, and also the gnu GCC compilers.

Which GCM model are you working with? We have done some work with a few so may be able to offer insight.
Could you compile with gcc?
Have you tried building with intel 2017?

There are various options for interfacing ML and Fortran, though we feel this is the most straightforward for research exploration with minimal additional knowledge required.
We advise against hard-coding in Fortran for reasons discussed in the presentations linked from our docs page eg. [here](https://jackatkinson.net/slides/IPSL_FTorch/IPSL_FTorch.html) ([recording](https://www.youtube.com/watch?v=-NJGuV6Rz6U)) and [here](https://jackatkinson.net/slides/RSECon23/RSECon23.html).

Let us know.

**Comment by KingLLee** [comment]
> Hi @KingLLee I'm not sure we stipulate anywhere that intel 2021 is required, can you tell us why you got that impression?
> 
> We have tested with various versions of the intel OneAPI suite, and also the gnu GCC compilers.
> 
> Which GCM model are you working with? We have done some work with a few so may be able to offer insight. Could you compile with gcc? Have you tried building with intel 2017?
> 
> There are various options for interfacing ML and Fortran, though we feel this is the most straightforward for research exploration with minimal additional knowledge required. We advise against hard-coding in Fortran for reasons discussed in the presentations linked from our docs page eg. [here](https://jackatkinson.net/slides/IPSL_FTorch/IPSL_FTorch.html) ([recording](https://www.youtube.com/watch?v=-NJGuV6Rz6U)) and [here](https://jackatkinson.net/slides/RSECon23/RSECon23.html).
> 
> Let us know.

Thanks for your replying @jatkinson1000
What I met with is that Ftorch can not be compiled with the compiler which does not support CXX 17, and of course different version of Intel compiler can solve this problem. I run a model based on cpl7 of cesm1.2 which requires intel 2017, and sadly intel 2017 cannot compile ftorch (I tried this before but failed, reporting that does not support CXX17). But high version of intel can do this (I used intel 2021 to compile).
I agree with you that ftorch is the most straightforward for embed AI model to fortran.
So I mean that I wonder how to solve this problem and whether ftorch can be compiled in low-version intel compiler like 2017 or not? I'm not familiar with compiler, so  you may be able to offer some suggestions. Thank you very much!

**Comment by jatkinson1000** [comment]
Thanks @KingLLee 

Thanks for the additional detail.
I am actually currently working with FTorch to couple to to CESM (but version 2).

I believe the restriction on compiler comes in due to how the Torch binary has been compiled.
How are you getting Torch - via a libtorch binary, or through pip installing in a venv?

Can you try installing via a venv and then building FTorch with your chosen compiler linking to Torch?
I believe this has worked for us with "cross-compiling".
If this doesn't work we can pursue further, with some error logs and minimum working examples.

**Comment by KingLLee** [comment]
Hi @jatkinson1000
I got Torch via a libtorch binary. I wonder if the version of intel compiler depends on the version of pytorch or libtorch? My libtorch version is 2.2.0.dev20231123+cpu. Maybe lower-version could work. 
I tried torch env before ( version 1.7), but encounter an error. Which version does Ftorch require?
Another question, that I note that "cross-compiling", do you mean that it could work when I compile Ftroch by using gnu and compile cesm by using intel?

**Comment by jatkinson1000** [comment]
Hi @KingLLee

That looks like the dev version of libtorch.
For starters I would definitely use a stable version (currently 2.1.2 see [here](https://pytorch.org/)) rather than the dev version.

By cross-compiling I mean you can use a Fortran compiler from one suite, and a C/C++ compiler from another.
Is always advised to compile the Fortran in FTorch with the same compiler that you will use for your application (here intel 2017).
Could you try building FTorch with the combination of `ifort` and `gcc`?

If you try the above could you then provide us with some further information on the errors you encounter?

**Comment by KingLLee** [comment]
Hi @jatkinson1000
I run this code before:
```
cd FTorch/src/
mkdir build3
cd build3
cmake .. -DCMAKE_PREFIX_PATH=/path/to/libtorch/share/cmake  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/path/to/private_module/FTorch3 -DCMAKE_Fortran_COMPILER=ifort -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc
make
```

As you can see in this picture:
"C++17 or later compatible compiler is required to use ATen"
Intel 2017 cannot support C++17, and I wonder if Ftorch MUST require c++17 or not. And if not ,I think I can try to use lower version libtorch (Now version 2.1.2+cpu).
Thanks for your patiently help!
![Snipaste_2023-12-21_23-02-11](https://github.com/Cambridge-ICCS/FTorch/assets/90272479/297743d7-9430-42ea-af92-d7d2099056b7)

**Comment by jatkinson1000** [comment]
Cool, thanks.
Can you try building FTorch with ifort and gnu C and C++ compilers?

As another approach can you use a more recent icc and icpc compiler to build FTorch (as this should not impact the CESM build) since any FTorch C code is called from FTorch Fortran.

**Comment by KingLLee** [comment]
Yes, it may cost sometime. @jatkinson1000
And I think I can ensure that Ftorch must require C++17 to compile as you can see in this picuture. Because some codes in Ftorch is suitable for newer C++. 
![Snipaste_2023-12-21_23-14-10](https://github.com/Cambridge-ICCS/FTorch/assets/90272479/9b18d62c-6576-4655-ab88-0163e05036c9)

**Comment by jatkinson1000** [comment]
Great, let me know when you have tried.

Binding to certain features of libtorch does require C++ >= 17 see [here](https://github.com/pytorch/pytorch#prerequisites) but if you can get a compatible gcc or icc on your system it should build fine.

**Comment by KingLLee** [comment]
Hi @jatkinson1000
Since my try, I have to use other methods except FTORCH to bind python to fortran..... My GCM does not support c++17 or newer... What a pity! I think the reason is mainly because of that FTORCH is based on c++17, 

I tried to rewrite the FTORCH code suitable for C++14 or older, but I'm not an expert in C++.

**Comment by jatkinson1000** [comment]
Hi @KingLLee As I reied to say, there should be no need to use the same C++ compiler for FTorch as you do for the GCM.
The only compiler that needs to match is the Fortran compiler.

So you should be able to build FTorch with icc and icpc 2021, or a C++17 compatible GCC, and ifort 2017.

You can then build CESM with ifort, icc, and icpc 2017 and link to FTorch.
You should be able to check this works by building one of our examples before trying something large like CESM.

If you want we could try and arrange a call in the new year to discuss?

**Comment by KingLLee** [comment]
Thanks for your patiently explain and help!
I can compile my model successfully. And I use older ifort (which is suitable for my GCM) and newer icpc to compile Ftorch. I found that Ftorch does not depend on newer version Fortran but I should set the same version ifort and different version icpc in compiling Ftorch and GCM which is neglected by me totally. I just use same newer version intel compiler for convenience . Thanks you again!

**Comment by jatkinson1000** [comment]
Wonderful, I am glad that this is now sorted for you. 😀
Are you happy for me to now close this issue as resolved?

I hope FTorch is useful, and please do get in touch in the future with any other questions or issues you have, or with any successes! - we list and link projects using FTorch on our main page.

**Comment by KingLLee** [comment]
Hi @jatkinson1000 
Of course, you can close this issue, and thank you again.

**Comment by jatkinson1000** [comment]
Closing as resolved 😁
