### ISSUE TITLE
Test on GPUs

### ISSUE THREAD

**Issue by mondus** [Cambridge-ICCS/FTorch#9]
Run the testing suite on a GPU system. Requires saving the torch script a bit differently? @jatkinson1000

**Comment by mondus** [comment]
This also requires the cmake to be updated to specify CUDA as a language. Some trickery is probably required to do this manually as we probably want it to be optional.

**Comment by ElliottKasoar** [comment]
Notes so far:

- I'll probably add it in case, but I don't think `enable_language(CUDA)` is required in CMakeLists.txt, as (for pip installed versions of torch, at least) it automatically detects whether to enable CUDA
  - A note about the different settings for `index-url` (e.g.  https://download.pytorch.org/whl/cpu or https://download.pytorch.org/whl/cu121) when using pip may be useful for both GPU and CPU-only users
- Warnings when running `make` for FTorch-benchmarks include:
  - /usr/bin/ld: warning: libgomp-a34b3233.so.1, needed by .../libtorch_cpu.so, not found (try using -rpath or -rpath-link)
  - /usr/bin/ld: warning: libcudart-9335f6a2.so.12, needed by .../libtorch_cuda.so, not found (try using -rpath or -rpath-link)
  - /usr/bin/ld: warning: libnvToolsExt-847d78f2.so.1, needed by .../libtorch_cuda.so, not found (try using -rpath or -rpath-link)
  - /usr/bin/ld: warning: libcudnn.so.8, needed by .../libtorch_cuda.so, not found (try using -rpath or -rpath-link)
  - These can be fixed using `export LD_LIBRARY_PATH="/path/to/venv/lib/python3.8/site-packages/torch/lib/:$LD_LIBRARY_PATH"`
  - cuDNN can also be loaded and linked separately, but this is non-trivial on CSD3, as torch/share/cmake/Caffe2/Modules_CUDA_fix/FindCUDNN.cmake searches for a version file of the form cudnn.h or cudnn_version.h, whereas the loaded cudnn/8.9_cuda-12.1 has a version file named cudnn_version_v8.h
- Changes required:
  - `torch_kCPU` -> `torch_kCUDA` in benchmarker_model_torch.f90 files to avoid `RuntimeError: Input type (CPUFloatType) and weight type (CUDAFloatType) should be the same`
  - `device = torch.device('cuda')` etc uncommented from respective pt2ts.py files and `saved_ts_filename` changed to ensure gpu TorchScript is saved
  - `.to(get_device(device))` is required in `torch_from_blob` in ctorch.cpp, to avoid `[ERROR]: The specified pointer resides on host memory and is not registered with any CUDA device.`
  - Something similar will be required to ensure output is correctly updated

**Comment by jatkinson1000** [comment]
When making changes to CMake we should probably add a build flag `-DGPU_BUILD` or similar to trigger the CUDA parts, as users may well want to build for non-cpu installations as well.
